### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by RuiciroRS** [khancyr/ardupilot_gazebo#14]
Hello, I'm trying to use the ardupilot_gazebo plugin on Ubuntu 18.04 and Gazebo 9, However after making the build directory and attempting to do: cmake .. it gives this error:

-- Checking for module 'bullet>=2.82'
--   No package 'bullet' found
-- Checking for module 'bullet2.82>=2.82'
--   No package 'bullet2.82' found
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:102 (message):
  Error: Bullet > 2.82 not found, please install libbullet2.82-dev.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by RuiciroRS** [comment]
Any idea on how to solve this?

**Comment by RuiciroRS** [comment]
Installed libbullet 2.87 package from: https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libbullet2.87_2.87+dfsg-2_amd64.deb.html but found no success

**Comment by jmtatsch** [comment]
did you clean and rebuild after installing?

**Comment by RuiciroRS** [comment]
Not entirely sure on it, I literally just installed the .deb package with: sudo dpkg -i libbullet2.87_2.87+dfsg-2_amd64.deb
And afterwards made the build dir and attempted to compile again

Could you give some advice on how to do so?

**Comment by ehiggins98** [comment]
I know this thread is really old and you've probably solved your problem, but I wanted to answer because I at least wasn't able to find an answer anywhere online.

For me, the problem was that the `bullet.pc` file wasn't in my `PKG_CONFIG_PATH`. I just ran `sudo find / -name "bullet.pc"` to find the file, then added that directory to `PKG_CONFIG_PATH` with `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:<folder containing bullet.pc>`. For example, for me the directory containing `bullet.pc` was `/usr/lib/x86_64-linux-gnu/pkgconfig/`, so I ran `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig/`, and then the cmake command ran successfully.

I hope that helps anybody who has this problem in the future!

**Comment by OkitaAqukinn** [comment]
Special thanks for you!!! I meet this issue too and finally solved here

**Comment by khancyr** [comment]
We migrated repo to https://github.com/ArduPilot/ardupilot_gazebo with much better version and support
